### ISSUE TITLE
Klein Consensus

### ISSUE THREAD

**Issue by xuansondao** [shihuili1218/klein#76]
When I run the example, I get a situation where the skipPrepare variable is null.
This error is because while you assign node object to self variable it cannot copy the value of that variable to your self variable. Series 137 class PaxosConsensus
this.self = (PaxosNode) logManager.loadMetaData(PaxosNode.Builder.aPaxosNode()

=> leading to a null error when running ProposerImpl at line 285, class ProposerImpl

**Comment by shihuili1218** [comment]
Yes, I noticed this bug. Because `transient` is used here.

https://github.com/shihuili1218/klein/blob/5bfc67c3f7cae3f122dfc832ee48991b1650d14f/klein-consensus/klein-consensus-paxos/src/main/java/com/ofcoder/klein/consensus/paxos/PaxosNode.java#L33

`transient` is required. It should not be persistence, but reset at startup. 

If you are interested, you can fix it.

**Comment by xuansondao** [comment]
Oki, Let me make a pull request to fix that.
